# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonDivider
                                 A QGIS plugin
 Polygon Divider is a plugin it takes a polygon and efficiently divides it into a number of 'squareish' polygons of a defined size
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-11
        copyright            : (C) 2023 by Muthu Rathnashri
        email                : rathnashri2004@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PolygonDivider class from file PolygonDivider.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .polygon_divider import PolygonDivider
    return PolygonDivider(iface)
